### ISSUE TITLE
[Request] GitHub Release

### ISSUE THREAD

**Issue by lambdalisue** [Code-Hex/battery#2]
[zplug/zplug](https://github.com/zplug/zplug) を利用しているので GitHub Release にバイナリファイルがあると嬉しいです。ご検討いただけると助かります。

**Comment by Code-Hex** [comment]
@lambdalisue リクエストありがとうございます！
現在、もう少し追加しないといけない機能があるので実装後バイナリで公開します！
ですのでもう少しお待ち下さい！

**Comment by 39e** [comment]
Go言語を実行できる環境であれば
```zsh
zplug "Code-Hex/battery", \
	as:command, \
	if:"(( $+commands[go] ))", \
	hook-build:"go build ./cmd/battery", \
	use:"battery"
```
のように記述すれば使えますよ

**Comment by Code-Hex** [comment]
@lambdalisue リリースしました！
https://github.com/Code-Hex/battery/releases
よろしければ close してください！
リクエストありがとうございました！

**Comment by ghost** [comment]
早速使わせていただきます!

**Comment by lambdalisue** [comment]
ありがとうございました！
